apiVersion: batch/v1
kind: Job
metadata:
  name: "k8s-example-v9"
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: "k8s-example"
        image: "deeplabepitro/k8s-example"
#        command: ["python main.py"]
        imagePullPolicy: IfNotPresent
      restartPolicy: Never


